"""
Phase 5: Report Generator — Compiles the validated research into a clean
final report with executive summary, findings, confidence ratings, and sources.

UPDATED: Now makes direct LLM API calls.
"""

from .llm_client import LLMClient


class ReportGenerator:
    """Generates the final research report."""

    def generate(self, topic: str, profile: str, history: list,
                 validation_result: str, challenge_result: str,
                 total_rounds: int, llm_client: LLMClient = None) -> str:
        """
        Generate the final report from validated research.

        Args:
            topic: Research topic
            profile: Final validated research profile
            history: List of round history dicts
            validation_result: Latest validation output
            challenge_result: Latest challenge output
            total_rounds: Number of adversarial rounds completed
            llm_client: LLM client for API calls

        Returns:
            Final report text
        """
        if llm_client:
            return self._generate_with_llm(topic, profile, history,
                                            validation_result, challenge_result,
                                            total_rounds, llm_client)
        else:
            return self._generate_fallback(topic, profile, history, total_rounds)

    def _generate_with_llm(self, topic: str, profile: str, history: list,
                            validation: str, challenge: str,
                            total_rounds: int, llm_client: LLMClient) -> str:
        """Use LLM to generate the final report."""
        history_text = ""
        for h in history:
            history_text += f"\n### Round {h['round']}\n"
            history_text += f"- Improvements found: {h['improvement_count']}\n"
            if h.get('improvement_points'):
                for p in h['improvement_points'][:5]:
                    history_text += f"  - {p}\n"
            history_text += f"- Validation: {h.get('validation_summary', 'N/A')[:200]}\n"
            history_text += f"- Challenge: {h.get('challenge_summary', 'N/A')[:200]}\n"

        system = (
            "You are a RESEARCH REPORT WRITER. Your job is to take a validated "
            "Research Profile and compile it into a professional, publication-ready "
            "final report. Be clear, accessible, and honest about limitations."
        )

        user_msg = f"""TOPIC: {topic}
ADVERSARIAL ROUNDS COMPLETED: {total_rounds}

VALIDATED RESEARCH PROFILE:
{profile[:12000]}

ADVERSARIAL HISTORY:
{history_text}

LATEST VALIDATION:
{validation[:3000]}

LATEST CHALLENGE:
{challenge[:3000]}

YOUR MISSION:
Create a polished final report that:
1. Synthesizes everything into a clear, readable narrative
2. Shows confidence levels for each major finding
3. Acknowledges what survived adversarial scrutiny and what didn't
4. Cites sources properly
5. Is accessible to a non-expert audience

OUTPUT FORMAT:

# Final Research Report: {topic}

## Executive Summary
2-3 paragraph overview of key findings and their confidence levels.

## Key Findings

### Finding 1: [Title]
- **What we found:** [clear statement]
- **Evidence strength:** [Strong/Moderate/Weak]
- **Sources:** [key sources]
- **Adversarial testing:** [how this survived validation/challenge]

### Finding 2: [Title]
[repeat format]

## Data & Statistics
Key numbers and metrics with sources.

## What Changed Through Adversarial Testing
Brief summary of how the research evolved through each round.

## Remaining Uncertainties
Honest assessment of what we still don't know or can't verify.

## Sources
Complete bibliography with URLs.

## Methodology Note
Brief description of the adversarial research process used.
- Number of research agents: {len(history)}
- Adversarial rounds: {total_rounds}
- Each round: Team A (validators) vs Team B (challengers)
- Research survived adversarial scrutiny before final report

---
*This report survived {total_rounds} rounds of adversarial interrogation.
Generated by No-Slop Research.*"""

        result = llm_client.chat(
            messages=[{"role": "user", "content": user_msg}],
            system=system,
            temperature=0.3,
            max_tokens=6000
        )

        if result["success"]:
            return result["content"]
        else:
            return self._generate_fallback(topic, profile, history, total_rounds)

    def _generate_fallback(self, topic: str, profile: str,
                            history: list, total_rounds: int) -> str:
        """Fallback report without LLM."""
        history_summary = ""
        for h in history:
            history_summary += f"- Round {h['round']}: {h['improvement_count']} improvements found\n"

        return f"""# Final Research Report: {topic}

## Executive Summary
This report was compiled from research that went through {total_rounds} adversarial rounds.
No LLM client was configured for final report generation — showing raw validated profile.

## Research Profile
{profile[:8000]}

## Adversarial History
{history_summary}

## Methodology Note
- Adversarial rounds: {total_rounds}
- Team A (validators) vs Team B (challengers) per round
- No LLM configured — raw output shown

---
*Generated by No-Slop Research*
"""

    def extract_findings_summary(self, report: str) -> dict:
        """Extract a structured summary of findings from the final report."""
        import re
        findings = []

        finding_pattern = r'### Finding \d+:\s*(.+?)(?=### Finding|\n## |\Z)'
        matches = re.findall(finding_pattern, report, re.DOTALL)

        for match in matches:
            lines = match.strip().split("\n")
            title = lines[0].strip()
            evidence = "unknown"
            for line in lines:
                if "evidence strength" in line.lower():
                    if "strong" in line.lower():
                        evidence = "strong"
                    elif "moderate" in line.lower():
                        evidence = "moderate"
                    elif "weak" in line.lower():
                        evidence = "weak"
            findings.append({"title": title, "evidence": evidence})

        return {
            "total_findings": len(findings),
            "strong": sum(1 for f in findings if f["evidence"] == "strong"),
            "moderate": sum(1 for f in findings if f["evidence"] == "moderate"),
            "weak": sum(1 for f in findings if f["evidence"] == "weak"),
            "findings": findings
        }
